version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: builder  # Use builder stage for development
    command: npm run dev
    volumes:
      - ./src:/app/src:ro
      - ./config:/app/config:ro
      - ./data:/app/data
    environment:
      - NODE_ENV=development
      - LOG_LEVEL=debug
      - AGREE_TOS=false  # Override for development 